### ISSUE TITLE
Main Feed feature

### ISSUE THREAD

**Issue by ZendyLim** [ZendyLim/junction-2019#7]
As a social media lurker that distrust social media,  
I want a news feed from reliable sources,  
so that I can consume information with minimum effort and minimum disinformation.

## Acceptance Criteria
- [ ] Show news feed after login
- [x] Show min 10 articles in the feed
- [ ] Sort the articles by the most recent
- [x] Each articles has a photo and a news title.
- [x] Each articles shows its topic on top of the card.

**Comment by dina-setiana** [comment]
# Devnotes
NewsAPI works.
Bitext Text and Sentiment Analysis works.
