### ISSUE TITLE
User Feedback on Article Feature

### ISSUE THREAD

**Issue by ZendyLim** [ZendyLim/junction-2019#9]
As a distrusting news consumer,  
I want some user generated information about reliability of an article,  
so that I can decide whether I can trust this article.

## Acceptance Criteria
- [x] The article title is on top of the page
- [ ] The article reliability score is shown beside the title.
- [ ] The reliability score is displayed by consuming the hoaxly api.
- [x] The article contents follows the title.
- [x] The user comments on the article are shown after the article contents.
- [x] The user can add a new comment in a textbox.
- [x] The user can rate the article TRUE or FAKE.
- [ ] The user must add a new comment when rating the article.

**Comment by dina-setiana** [comment]
# Devnote
Hoaxy works.
